properties:
  error: boolean
  message: string
  data: array
  code: integer
example:
  error: false
  message: "Se generaron los procesos de evaluación de manera correcta."
  data: {
    'process_id': 452154545
  }
  code: 2000
