properties:
  application_id:
    type: integer
    description: Application Indentifier
  applicant_id:
    type: integer
    description: Applicant Indentifier
  company_id:
    type: integer
    description: Company Identifier
  job_id:
    type: integer
    description: Announcement Identifier
  evaluation_ids:
    type: array
    description: Evaluation Identifier list
example:
  application_id: 542154545
  applicant_id: 124578451
  company_id: 124512
  job_id: 1245124515
  evaluation_ids: ['COM', 'CON', 'ING']
